name: CI

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'tests/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'compute_rossby_spectrum.jl'
      - '.github/workflows/ci.yml'
    tags: '*'
  pull_request:
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'tests/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'compute_rossby_spectrum.jl'
      - '.github/workflows/ci.yml'

jobs:
  test:
    name: RossbyWaveSpectrum - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10.2'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
