name: Documentation
on:
  push:
    branches:
      - master
    tags: '*'
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'docs/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'docs/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10.2'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(; path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
