name: Install

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CITATION.bib'
      - '.github/workflows/TagBot.yml'
    tags: '*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CITATION.bib'
      - '.github/workflows/TagBot.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install the project
        run: ./INSTALL.sh

