name: Install

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'RossbyPlots/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'INSTALL.sh'
      - 'installjulia.sh'
      - 'juliaversion'
      - '.github/workflows/install.yml'
    tags: '*'
  pull_request:
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'RossbyPlots/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'INSTALL.sh'
      - 'installjulia.sh'
      - 'juliaversion'
      - '.github/workflows/install.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install the project
        run: ./INSTALL.sh
      - name: Install for a different julia version
        run: ./INSTALL.sh 1.10.0

