name: Install

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'RossbyPlots/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'INSTALL.sh'
      - 'installjulia.sh'
      - 'juliaversion'
      - '.github/workflows/install.yml'
    tags: '*'
  pull_request:
    paths:
      - 'ApproxFunAssociatedLegendre/**'
      - 'src/**'
      - 'RossbyPlots/**'
      - 'Project.toml'
      - 'Manifest.toml'
      - 'INSTALL.sh'
      - 'installjulia.sh'
      - 'juliaversion'
      - '.github/workflows/install.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install the project
        run: |
          ./INSTALL.sh
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.2" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.2"' ]; then exit 1; fi
      - name: Install for a different julia version
        run: |
          ./INSTALL.sh -v 1.10.0
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.0" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.2"' ]; then exit 1; fi
      - name: Install and resolve for a different julia version
        run: |
          ./INSTALL.sh -v 1.10.0 -r
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.0" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.0"' ]; then exit 1; fi
      - name: Reinstall the project
        run: |
          ./INSTALL.sh -r
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.2" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.2"' ]; then exit 1; fi
      - name: Install for a different julia version (positional)
        run: |
          ./INSTALL.sh 1.10.0
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.0" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.2"' ]; then exit 1; fi
      - name: Install and resolve for a different julia version (positional)
        run: |
          ./INSTALL.sh 1.10.0 -r
          if [ "$(cat juliaversioninstalled)" != "RossbyWaveJuliaVersion=1.10.0" ]; then exit 1; fi
          if [ "$(grep julia_version Manifest.toml)" != 'julia_version = "1.10.0"' ]; then exit 1; fi

